// PRO MAX OS – Complete project export packager.
// Produces a clean source zip + PROJECT-CONTEXT.md (+ optional concatenated sources)
// to develop the project on Claude AI (claude.ai upload or Claude Code).
//
// Usage:
//   node scripts/export-project.mjs            -> dist/export/PRO-MAX-OS-export.zip + PROJECT-CONTEXT.md
//   node scripts/export-project.mjs --full     -> also builds SOURCES-ALL.md (every source file)
//   node scripts/export-project.mjs --out <dir>
//
// No dependencies. Zip is written by a built-in STORE-method writer, so it works on
// any Node >= 14 without external tools.

import { promises as fs } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(process.cwd());
const args = process.argv.slice(2);
const OUT_DIR = path.resolve(args.includes('--out') ? args[args.indexOf('--out') + 1] : path.join(ROOT, 'dist', 'export'));
const FULL = args.includes('--full');

const EXCLUDED_NAMES = new Set([
  '.git', '.hg', '.svn', 'node_modules', 'target', 'dist', 'gen', 'build', 'out',
  '.webpack', '.turbo', '.cache', '.parcel-cache', '.next', '.nuxt', 'logs', 'tmp',
  '.idea', '.vscode', 'coverage', 'debug',
]);
const EXCLUDED_EXTS = new Set(['.db', '.db-journal', '.db-wal', '.db-shm', '.log', '.zip', '.apk', '.exe', '.dll', '.pdb', '.o', '.rlib', '.rmeta', '.class']);
const TEXT_EXTS = new Set(['.rs', '.ts', '.tsx', '.js', '.jsx', '.mjs', '.cjs', '.json', '.html', '.css', '.sql', '.md', '.toml', '.yml', '.yaml', '.env', '.conf', '.config', '.txt', '.svg', '.xml']);

async function collect(baseDir) {
  const files = [];
  async function walk(dir) {
    let entries;
    try {
      entries = await fs.readdir(dir, { withFileTypes: true });
    } catch {
      return;
    }
    for (const e of entries) {
      const full = path.join(dir, e.name);
      if (e.isDirectory()) {
        if (EXCLUDED_NAMES.has(e.name)) continue;
        await walk(full);
      } else {
        if (EXCLUDED_EXTS.has(path.extname(e.name).toLowerCase())) continue;
        if (e.name === '.env' || e.name.startsWith('.env.')) continue;
        files.push(path.relative(baseDir, full).replaceAll(path.sep, '/'));
      }
    }
  }
  await walk(baseDir);
  return files.sort();
}

// ── Minimal ZIP writer (STORE method, UTF-8 names) ──────────────────────
function crc32(buf) {
  let c = 0xffffffff;
  for (let i = 0; i < buf.length; i++) {
    c ^= buf[i];
    for (let k = 0; k < 8; k++) c = (c >>> 1) ^ (0xedb88320 & -(c & 1));
  }
  return (c ^ 0xffffffff) >>> 0;
}

function zip(files) {
  const parts = [];
  const central = [];
  let offset = 0;
  for (const f of files) {
    const nameBuf = Buffer.from(f.name, 'utf8');
    const data = f.data;
    const crc = crc32(data);
    const lh = Buffer.alloc(30);
    lh.writeUInt32LE(0x04034b50, 0);
    lh.writeUInt16LE(20, 4);
    lh.writeUInt16LE(0x0800, 6);
    lh.writeUInt16LE(0, 8);
    lh.writeUInt16LE(0, 10);
    lh.writeUInt16LE(0, 12);
    lh.writeUInt32LE(crc, 14);
    lh.writeUInt32LE(data.length, 18);
    lh.writeUInt32LE(data.length, 22);
    lh.writeUInt16LE(nameBuf.length, 26);
    lh.writeUInt16LE(0, 28);
    const local = Buffer.concat([lh, nameBuf, data]);
    parts.push(local);
    central.push({ nameBuf, crc, size: data.length, offset });
    offset += local.length;
  }
  const cdStart = offset;
  const cdHeaders = central.map((c) => {
    const ch = Buffer.alloc(46);
    ch.writeUInt32LE(0x02014b50, 0);
    ch.writeUInt16LE(20, 4);
    ch.writeUInt16LE(20, 6);
    ch.writeUInt16LE(0x0800, 8);
    ch.writeUInt16LE(0, 10);
    ch.writeUInt16LE(0, 12);
    ch.writeUInt16LE(0, 14);
    ch.writeUInt32LE(c.crc, 16);
    ch.writeUInt32LE(c.size, 20);
    ch.writeUInt32LE(c.size, 24);
    ch.writeUInt16LE(c.nameBuf.length, 28);
    ch.writeUInt16LE(0, 30);
    ch.writeUInt16LE(0, 32);
    ch.writeUInt16LE(0, 34);
    ch.writeUInt16LE(0, 36);
    ch.writeUInt32LE(0, 38);
    ch.writeUInt32LE(c.offset, 42);
    return Buffer.concat([ch, c.nameBuf]);
  });
  const cdSize = cdHeaders.reduce((n, b) => n + b.length, 0);
  const end = Buffer.alloc(22);
  end.writeUInt32LE(0x06054b50, 0);
  end.writeUInt16LE(0, 4);
  end.writeUInt16LE(0, 6);
  end.writeUInt16LE(central.length, 8);
  end.writeUInt16LE(central.length, 10);
  end.writeUInt32LE(cdSize, 12);
  end.writeUInt32LE(cdStart, 16);
  end.writeUInt16LE(0, 20);
  return Buffer.concat([...parts, ...cdHeaders, end]);
}

// ── Context document ────────────────────────────────────────────────────
async function buildContext(files) {
  const rs = files.filter((f) => f.endsWith('.rs'));
  const ts = files.filter((f) => f.endsWith('.ts') || f.endsWith('.tsx'));
  const stats = { rs: rs.length, ts: ts.length, total: files.length };
  return [
    '# PRO MAX OS — Project Context for Claude AI',
    '',
    '> Generated by `node scripts/export-project.mjs`. Load this file into the Claude',
    '> conversation (or copy it to the repo root as `CLAUDE.md` so Claude Code picks it up automatically).',
    '',
    '## What this is',
    'PRO MAX OS v2.0.0 — a professional Manufacturing ERP for a paper-cup / carton packaging',
    'factory in Oman. Desktop (Tauri 2 / Rust + React + TypeScript), web API, Android APK, and a',
    'mobile PWA. Arabic/English, OMR (Rial) currency, VAT-aware, fully offline-capable (local SQLite).',
    '',
    '## Tech stack',
    '- Backend: Rust, Tauri 2, rusqlite (SQLite bundled), argon2 + JWT (jsonwebtoken), AES-256-GCM, calamine (Excel), reqwest (rustls), chrono, tokio.',
    '- Frontend: React 18 + TypeScript + Vite, Zustand, i18next (ar/en), Tailwind, framer-motion, recharts.',
    '- Extra binaries: `promax-api` (REST API + static PWA serving), `promax-mcp` (MCP server).',
    '- Mobile: hand-written PWA under `mobile/` (no framework) + Tauri Android build (`src-tauri/gen`).',
    '- CI: `.github/workflows/ci.yml` (cargo check + test on windows-latest).',
    '',
    '## Build / run / test',
    '- Desktop dev: `npm run dev` (starts Vite + Tauri)',
    '- Desktop build: `npm run tauri build`',
    '- Frontend build: `npm run build` (runs `tsc && vite build`)',
    '- Lint: `npm run lint` (eslint)  ·  i18n: `node scripts/check-i18n.mjs`',
    '- Backend tests: `cargo test --lib` (run inside `src-tauri/`)',
    '- API server: `cargo run --bin promax-api -- --port 8080 --mobile-dir ../mobile` (env: PROMAX_DB_PATH, PROMAX_JWT_SECRET)',
    '- MCP server: `cargo run --bin promax-mcp`',
    '- Android APK: `cargo tauri android build --apk` (needs Android SDK + cargo-ndk)',
    '',
    '## Architecture',
    '- `src-tauri/src/` — Rust core (lib). `commands/` = one module per domain (invoices, products, hr, production, ai_*, ...).',
    '- `src-tauri/src/db.rs` — SQLite schema/migrations (`SCHEMA_VERSION = 24`), ~90 tables. `schema.sql` holds the DDL.',
    '- `src-tauri/src/crypto.rs` — Argon2id password hashing, JWT (jti blacklist), AES-256-GCM secrets, machine-bound licensing.',
    '- `src-tauri/src/bin/api_server.rs` — hardened REST API v3 (rate limiting, security headers, RBAC, audit trail) + serves `mobile/` PWA.',
    '- `src-tauri/src/commands/ai_providers.rs` — 7 AI engines (ollama, groq, gemini, deepseek, mistral, openai, anthropic) with failover.',
    '- `src-tauri/src/commands/ai_file_import.rs` — AI document/file import (analyze -> map -> commit into customers/products/invoices/stock/expenses...).',
    '- `src/` — React app. `pages/<domain>/`, `components/ui`, `stores/` (Zustand), `i18n/locales/{ar,en}.json` (2143 keys each).',
    '- `mobile/` — self-contained PWA (no build step): `app.js`, `styles.css`, `index.html`, `sw.js`, `manifest.webmanifest`, icons, signed APK.',
    '',
    '## Feature inventory (highlights)',
    '- Accounting: chart of accounts, journal, trial balance, financial statements, daily closing, VAT return, owner summary.',
    '- Sales/Purchase: invoices (VAT), credit notes, payments + allocations, cheques, petty cash, cash/bank, barter exchange.',
    '- Inventory: multi-warehouse, stock transfers, price lists, adjustments, low stock, cost/margin.',
    '- Manufacturing: BOM, production orders (live progress), operation/maintenance daily sheets, machines, quality inspections.',
    '- HR: employees, payroll runs, advances, overtime, renewals, expiring contracts.',
    '- Operations: operating advances, import shipments + cost allocation, installments, renewals, government dashboard.',
    '- AI: assistant (chat w/ provider selection), file import (any file -> structured data), OCR, Excel/historical import, e-invoice.',
    '- Security: RBAC roles/permissions, audit logs, doc workflow statuses + approvals, license activation, backups.',
    '',
    '## Key files to know first',
    'src-tauri/src/lib.rs · src-tauri/src/db.rs · src-tauri/src/crypto.rs · src-tauri/src/bin/api_server.rs · src-tauri/src/commands/mod.rs · src-tauri/src/commands/ai_providers.rs · src-tauri/src/commands/ai_file_import.rs · src/App.tsx · src/components/layout/AppLayout.tsx · src/stores/authStore.ts · src/i18n/locales/ar.json · mobile/app.js',
    '',
    '## Conventions & guardrails',
    '- Arabic-first UI strings are in i18n files; always keep ar/en key counts in sync (run `node scripts/check-i18n.mjs`).',
    '- All new commands must be registered in `commands/mod.rs` and `lib.rs`.',
    '- Clippy-clean for new Rust files; no `unwrap()` on user input; money is stored as integer milli (amount_milli), never floats in SQLite.',
    '- Never commit secrets: PROMAX_JWT_SECRET, DB paths, API keys stay in env/files excluded from git.',
    '- Keep `mobile/` self-contained (no build step) and the API serving it hardened (path traversal guards, rate limits).',
    '',
    `## Snapshot stats (at export time)`,
    `- Rust files: ${stats.rs} · TS/TSX files: ${stats.ts} · tracked+untracked source files in export: ${stats.total}`,
    '',
  ].join('\n');
}

async function readText(f) {
  try {
    return await fs.readFile(path.join(ROOT, f), 'utf8');
  } catch {
    return '';
  }
}

// ── Main ────────────────────────────────────────────────────────────────
const files = await collect(ROOT);
await fs.mkdir(OUT_DIR, { recursive: true });

const entries = [];
for (const f of files) {
  const buf = await fs.readFile(path.join(ROOT, f));
  entries.push({ name: f, data: buf });
}

const zipPath = path.join(OUT_DIR, 'PRO-MAX-OS-export.zip');
await fs.writeFile(zipPath, zip(entries));

const ctx = await buildContext(files);
await fs.writeFile(path.join(OUT_DIR, 'PROJECT-CONTEXT.md'), ctx);

if (FULL) {
  const all = [];
  for (const f of files) {
    const ext = path.extname(f).toLowerCase();
    if (!TEXT_EXTS.has(ext)) continue;
    const txt = await readText(f);
    all.push(`\n\n/* ===== ${f} ===== */\n\n${txt}`);
  }
  await fs.writeFile(path.join(OUT_DIR, 'SOURCES-ALL.md'), all.join(''));
}

const sizeMB = (entries.reduce((n, e) => n + e.data.length, 0) / 1048576).toFixed(2);
console.log('Exported files:', entries.length, '(' + sizeMB + ' MB raw)');
console.log('ZIP   :', zipPath, '(' + (await fs.stat(zipPath)).size.toFixed(0) + ' bytes)');
console.log('CTX   :', path.join(OUT_DIR, 'PROJECT-CONTEXT.md'));
if (FULL) console.log('FULL  :', path.join(OUT_DIR, 'SOURCES-ALL.md'));
